### PR TITLE
Update to 2.9.4

### PR DESCRIPTION
**Pull request by Wgil**
It updates to the latest version of the original package

### CODE REVIEW

**Comment by cezarderevlean** [comment]
Built and published on npm.

**Comment by Wgil** [comment]
It seems flags are not being shown for the built version @cezarderevlean

**Comment by cezarderevlean** [comment]
Can you investigate? You'd have to pull latest and run `yarn install` and `yarn
build` on your local.

**Comment by Wgil** [comment]
Sure, I'll have a look

**Pull request merged**
